//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PessoaServiceSoapReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://tempuri.org/")]
    public partial class Pessoa : object
    {
        
        private string IdPessoaField;
        
        private string NomeField;
        
        private string EmailField;
        
        private string SenhaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IdPessoa
        {
            get
            {
                return this.IdPessoaField;
            }
            set
            {
                this.IdPessoaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Senha
        {
            get
            {
                return this.SenhaField;
            }
            set
            {
                this.SenhaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PessoaServiceSoapReference.PessoaServiceSoap")]
    public interface PessoaServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaPessoas", ReplyAction="*")]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.BuscaPessoasResponse> BuscaPessoasAsync(PessoaServiceSoapReference.BuscaPessoasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscaporEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.BuscaporEmailResponse> BuscaporEmailAsync(PessoaServiceSoapReference.BuscaporEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InserirPessoa", ReplyAction="*")]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.InserirPessoaResponse> InserirPessoaAsync(PessoaServiceSoapReference.InserirPessoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterarPessoa", ReplyAction="*")]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.AlterarPessoaResponse> AlterarPessoaAsync(PessoaServiceSoapReference.AlterarPessoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletarPessoa", ReplyAction="*")]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.DeletarPessoaResponse> DeletarPessoaAsync(PessoaServiceSoapReference.DeletarPessoaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscaPessoasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscaPessoas", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.BuscaPessoasRequestBody Body;
        
        public BuscaPessoasRequest()
        {
        }
        
        public BuscaPessoasRequest(PessoaServiceSoapReference.BuscaPessoasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BuscaPessoasRequestBody
    {
        
        public BuscaPessoasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscaPessoasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscaPessoasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.BuscaPessoasResponseBody Body;
        
        public BuscaPessoasResponse()
        {
        }
        
        public BuscaPessoasResponse(PessoaServiceSoapReference.BuscaPessoasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscaPessoasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PessoaServiceSoapReference.Pessoa[] BuscaPessoasResult;
        
        public BuscaPessoasResponseBody()
        {
        }
        
        public BuscaPessoasResponseBody(PessoaServiceSoapReference.Pessoa[] BuscaPessoasResult)
        {
            this.BuscaPessoasResult = BuscaPessoasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscaporEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscaporEmail", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.BuscaporEmailRequestBody Body;
        
        public BuscaporEmailRequest()
        {
        }
        
        public BuscaporEmailRequest(PessoaServiceSoapReference.BuscaporEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscaporEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public BuscaporEmailRequestBody()
        {
        }
        
        public BuscaporEmailRequestBody(string email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscaporEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscaporEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.BuscaporEmailResponseBody Body;
        
        public BuscaporEmailResponse()
        {
        }
        
        public BuscaporEmailResponse(PessoaServiceSoapReference.BuscaporEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscaporEmailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PessoaServiceSoapReference.Pessoa BuscaporEmailResult;
        
        public BuscaporEmailResponseBody()
        {
        }
        
        public BuscaporEmailResponseBody(PessoaServiceSoapReference.Pessoa BuscaporEmailResult)
        {
            this.BuscaporEmailResult = BuscaporEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirPessoaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirPessoa", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.InserirPessoaRequestBody Body;
        
        public InserirPessoaRequest()
        {
        }
        
        public InserirPessoaRequest(PessoaServiceSoapReference.InserirPessoaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirPessoaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senha;
        
        public InserirPessoaRequestBody()
        {
        }
        
        public InserirPessoaRequestBody(string nome, string email, string senha)
        {
            this.nome = nome;
            this.email = email;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirPessoaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirPessoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.InserirPessoaResponseBody Body;
        
        public InserirPessoaResponse()
        {
        }
        
        public InserirPessoaResponse(PessoaServiceSoapReference.InserirPessoaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirPessoaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InserirPessoaResult;
        
        public InserirPessoaResponseBody()
        {
        }
        
        public InserirPessoaResponseBody(string InserirPessoaResult)
        {
            this.InserirPessoaResult = InserirPessoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarPessoaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterarPessoa", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.AlterarPessoaRequestBody Body;
        
        public AlterarPessoaRequest()
        {
        }
        
        public AlterarPessoaRequest(PessoaServiceSoapReference.AlterarPessoaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarPessoaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senha;
        
        public AlterarPessoaRequestBody()
        {
        }
        
        public AlterarPessoaRequestBody(string nome, string email, string senha)
        {
            this.nome = nome;
            this.email = email;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterarPessoaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AlterarPessoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.AlterarPessoaResponseBody Body;
        
        public AlterarPessoaResponse()
        {
        }
        
        public AlterarPessoaResponse(PessoaServiceSoapReference.AlterarPessoaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AlterarPessoaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AlterarPessoaResult;
        
        public AlterarPessoaResponseBody()
        {
        }
        
        public AlterarPessoaResponseBody(string AlterarPessoaResult)
        {
            this.AlterarPessoaResult = AlterarPessoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletarPessoaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletarPessoa", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.DeletarPessoaRequestBody Body;
        
        public DeletarPessoaRequest()
        {
        }
        
        public DeletarPessoaRequest(PessoaServiceSoapReference.DeletarPessoaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletarPessoaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public DeletarPessoaRequestBody()
        {
        }
        
        public DeletarPessoaRequestBody(string email)
        {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletarPessoaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletarPessoaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PessoaServiceSoapReference.DeletarPessoaResponseBody Body;
        
        public DeletarPessoaResponse()
        {
        }
        
        public DeletarPessoaResponse(PessoaServiceSoapReference.DeletarPessoaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletarPessoaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeletarPessoaResult;
        
        public DeletarPessoaResponseBody()
        {
        }
        
        public DeletarPessoaResponseBody(string DeletarPessoaResult)
        {
            this.DeletarPessoaResult = DeletarPessoaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PessoaServiceSoapChannel : PessoaServiceSoapReference.PessoaServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PessoaServiceSoapClient : System.ServiceModel.ClientBase<PessoaServiceSoapReference.PessoaServiceSoap>, PessoaServiceSoapReference.PessoaServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PessoaServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PessoaServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), PessoaServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PessoaServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PessoaServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PessoaServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PessoaServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PessoaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.BuscaPessoasResponse> PessoaServiceSoapReference.PessoaServiceSoap.BuscaPessoasAsync(PessoaServiceSoapReference.BuscaPessoasRequest request)
        {
            return base.Channel.BuscaPessoasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PessoaServiceSoapReference.BuscaPessoasResponse> BuscaPessoasAsync()
        {
            PessoaServiceSoapReference.BuscaPessoasRequest inValue = new PessoaServiceSoapReference.BuscaPessoasRequest();
            inValue.Body = new PessoaServiceSoapReference.BuscaPessoasRequestBody();
            return ((PessoaServiceSoapReference.PessoaServiceSoap)(this)).BuscaPessoasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.BuscaporEmailResponse> PessoaServiceSoapReference.PessoaServiceSoap.BuscaporEmailAsync(PessoaServiceSoapReference.BuscaporEmailRequest request)
        {
            return base.Channel.BuscaporEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<PessoaServiceSoapReference.BuscaporEmailResponse> BuscaporEmailAsync(string email)
        {
            PessoaServiceSoapReference.BuscaporEmailRequest inValue = new PessoaServiceSoapReference.BuscaporEmailRequest();
            inValue.Body = new PessoaServiceSoapReference.BuscaporEmailRequestBody();
            inValue.Body.email = email;
            return ((PessoaServiceSoapReference.PessoaServiceSoap)(this)).BuscaporEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.InserirPessoaResponse> PessoaServiceSoapReference.PessoaServiceSoap.InserirPessoaAsync(PessoaServiceSoapReference.InserirPessoaRequest request)
        {
            return base.Channel.InserirPessoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PessoaServiceSoapReference.InserirPessoaResponse> InserirPessoaAsync(string nome, string email, string senha)
        {
            PessoaServiceSoapReference.InserirPessoaRequest inValue = new PessoaServiceSoapReference.InserirPessoaRequest();
            inValue.Body = new PessoaServiceSoapReference.InserirPessoaRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.email = email;
            inValue.Body.senha = senha;
            return ((PessoaServiceSoapReference.PessoaServiceSoap)(this)).InserirPessoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.AlterarPessoaResponse> PessoaServiceSoapReference.PessoaServiceSoap.AlterarPessoaAsync(PessoaServiceSoapReference.AlterarPessoaRequest request)
        {
            return base.Channel.AlterarPessoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PessoaServiceSoapReference.AlterarPessoaResponse> AlterarPessoaAsync(string nome, string email, string senha)
        {
            PessoaServiceSoapReference.AlterarPessoaRequest inValue = new PessoaServiceSoapReference.AlterarPessoaRequest();
            inValue.Body = new PessoaServiceSoapReference.AlterarPessoaRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.email = email;
            inValue.Body.senha = senha;
            return ((PessoaServiceSoapReference.PessoaServiceSoap)(this)).AlterarPessoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PessoaServiceSoapReference.DeletarPessoaResponse> PessoaServiceSoapReference.PessoaServiceSoap.DeletarPessoaAsync(PessoaServiceSoapReference.DeletarPessoaRequest request)
        {
            return base.Channel.DeletarPessoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PessoaServiceSoapReference.DeletarPessoaResponse> DeletarPessoaAsync(string email)
        {
            PessoaServiceSoapReference.DeletarPessoaRequest inValue = new PessoaServiceSoapReference.DeletarPessoaRequest();
            inValue.Body = new PessoaServiceSoapReference.DeletarPessoaRequestBody();
            inValue.Body.email = email;
            return ((PessoaServiceSoapReference.PessoaServiceSoap)(this)).DeletarPessoaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PessoaServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PessoaServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PessoaServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54222/PessoaService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PessoaServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54222/PessoaService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PessoaServiceSoap,
            
            PessoaServiceSoap12,
        }
    }
}
